const fs = require('fs');

const idPath = '/Applications/laravel/jobportal/lang/id.json';
const enPath = '/Applications/laravel/jobportal/lang/en.json';

const idData = JSON.parse(fs.readFileSync(idPath, 'utf8'));
const enData = JSON.parse(fs.readFileSync(enPath, 'utf8'));

const newId = {
    "admin.assessment.index.title": "Bank Soal Assessment",
    "admin.assessment.index.desc": "Kelola soal quiz per skill. Klik Detail untuk melihat dan mengelola soal dalam satu skill.",
    "admin.assessment.index.btn_add": "Tambah / Generate Soal",
    "admin.assessment.index.total_questions": "total soal",
    "admin.assessment.index.skills_with_questions": "skill memiliki soal",
    "admin.assessment.index.section_with_questions": "Skill dengan soal",
    "admin.assessment.index.section_without_questions": "Skill belum ada soal",
    "admin.assessment.index.btn_generate": "Generate",
    "admin.assessment.index.empty_title": "Belum ada skill",
    "admin.assessment.index.empty_desc": "Tambah skill terlebih dahulu di menu Skills.",
    "admin.assessment.index.card_active": "aktif",
    "admin.assessment.index.card_inactive": "nonaktif",
    "admin.assessment.index.btn_detail": "Detail",
    
    "admin.assessment.show.title": "Bank Soal: {skill}",
    "admin.assessment.show.desc": "{total} soal tersedia. Kelola, edit, atau hapus soal untuk skill ini.",
    "admin.assessment.show.search_placeholder": "Cari pertanyaan...",
    "admin.assessment.show.btn_search": "Cari",
    "admin.assessment.show.filter_level": "Level",
    "admin.assessment.show.filter_level_all": "Semua level",
    "admin.assessment.show.filter_status": "Status",
    "admin.assessment.show.filter_status_all": "Semua status",
    "admin.assessment.show.status_active": "Aktif",
    "admin.assessment.show.status_inactive": "Nonaktif",
    "admin.assessment.show.empty_title": "Belum ada soal",
    "admin.assessment.show.empty_desc": "Generate soal dengan AI atau tambah manual.",
    "admin.assessment.show.btn_generate_ai": "Generate dengan AI",
    "admin.assessment.show.dialog_delete_title": "Hapus soal?",
    "admin.assessment.show.dialog_delete_desc": "Soal ini akan dihapus permanen dari bank soal.",
    "admin.assessment.show.btn_cancel": "Batal",
    "admin.assessment.show.btn_delete": "Hapus",
    "admin.assessment.show.btn_deleting": "Menghapus...",
    "admin.assessment.show.btn_edit": "Edit",
    
    "admin.assessment.form.skill": "Skill",
    "admin.assessment.form.skill_placeholder": "Pilih skill",
    "admin.assessment.form.level": "Level",
    "admin.assessment.form.mode": "Mode Input",
    "admin.assessment.form.mode_manual": "Manual (1 soal)",
    "admin.assessment.form.mode_ai": "Generate AI (batch)",
    "admin.assessment.form.ai_count": "Jumlah Soal AI",
    "admin.assessment.form.manual_title": "Soal Manual ({count})",
    "admin.assessment.form.btn_add_manual": "Tambah Soal",
    "admin.assessment.form.question_num": "Pertanyaan #{num}",
    "admin.assessment.form.btn_remove": "Hapus",
    "admin.assessment.form.question": "Pertanyaan",
    "admin.assessment.form.question_placeholder": "Masukkan pertanyaan",
    "admin.assessment.form.option_a": "Opsi A",
    "admin.assessment.form.option_b": "Opsi B",
    "admin.assessment.form.option_c": "Opsi C",
    "admin.assessment.form.option_d": "Opsi D",
    "admin.assessment.form.correct_answer": "Jawaban Benar",
    "admin.assessment.form.is_active": "Soal aktif",
    "admin.assessment.form.btn_saving": "Menyimpan...",
    "admin.assessment.form.btn_save_ai": "Generate Soal AI",
    "admin.assessment.form.btn_save_manual": "Simpan Soal",
    "admin.assessment.form.search_skill": "Cari skill...",
    "admin.assessment.form.skill_not_found": "Skill tidak ditemukan.",

    "admin.pricing.form.section_info_title": "Informasi Paket",
    "admin.pricing.form.section_info_desc": "Nama paket kandidat, harga topup, dan status publikasi.",
    "admin.pricing.form.name": "Nama Paket",
    "admin.pricing.form.name_placeholder": "Contoh: Topup AI 5.000 Token",
    "admin.pricing.form.desc": "Deskripsi",
    "admin.pricing.form.desc_placeholder": "Jelaskan kegunaan paket ini untuk kandidat.",
    "admin.pricing.form.price": "Harga",
    "admin.pricing.form.default_free": "Paket gratis default",
    "admin.pricing.form.default_free_desc": "Dipakai untuk akses CV Builder pertama kandidat.",
    "admin.pricing.form.is_active": "Paket aktif",
    "admin.pricing.form.is_active_desc": "Paket bisa ditampilkan di flow pricing kandidat.",
    "admin.pricing.form.section_quota_title": "Kuota Paket",
    "admin.pricing.form.section_quota_desc": "Tentukan jumlah token AI dan kuota penggunaan CV Builder.",
    "admin.pricing.form.ai_token": "Jumlah token AI",
    "admin.pricing.form.cv_quota": "Kuota CV Builder",
    "admin.pricing.form.section_benefit_title": "Benefit Paket",
    "admin.pricing.form.section_benefit_desc": "Tulis satu benefit per baris agar tampil jelas di halaman pricing.",
    "admin.pricing.form.btn_add_benefit": "Tambah Benefit",
    "admin.pricing.form.benefit_placeholder": "Contoh: 1x CV Builder tambahan",
    "admin.pricing.form.preview_title": "Preview Paket",
    "admin.pricing.form.status_active": "Aktif",
    "admin.pricing.form.status_inactive": "Nonaktif",
    "admin.pricing.form.preview_name_empty": "Nama Paket Kandidat",
    "admin.pricing.form.preview_price_desc": "harga paket",
    "admin.pricing.form.badge_free": "Paket Gratis Default",
    "admin.pricing.form.badge_topup": "Paket Topup",
    "admin.pricing.form.section_save_title": "Simpan Perubahan",
    "admin.pricing.form.section_save_desc": "Setelah tersimpan, notifikasi Sonner akan muncul otomatis.",
    "admin.pricing.form.btn_saving": "Menyimpan...",
    "admin.pricing.form.btn_save": "Simpan Paket",
    "admin.pricing.form.error_toast": "Periksa kembali data pricing kandidat.",

    "admin.pricing.show.badge_free": "Gratis Default",
    "admin.pricing.show.badge_topup": "Topup",
    "admin.pricing.show.status_active": "Aktif",
    "admin.pricing.show.status_inactive": "Nonaktif",
    "admin.pricing.show.section_title": "Pricing Kandidat",
    "admin.pricing.show.price_desc": "harga paket",
    "admin.pricing.show.empty_desc": "Tidak ada deskripsi paket.",
    "admin.pricing.show.empty_benefit": "Belum ada benefit ditulis.",
    "admin.pricing.show.audit_title": "Audit Ringkas",
    "admin.pricing.show.audit_created": "Dibuat",
    "admin.pricing.show.audit_updated": "Terakhir update",
    "admin.pricing.show.audit_status": "Status",
    "admin.pricing.show.metric_ai": "Token AI",
    "admin.pricing.show.metric_cv": "Kuota CV Builder",
    "admin.pricing.show.metric_type": "Tipe Paket",
    "admin.pricing.show.type_free": "Gratis",
    "admin.pricing.show.type_topup": "Topup",

    "admin.pricing.index.btn_add": "Tambah Menu"
};

const newEn = {
    "admin.assessment.index.title": "Assessment Question Bank",
    "admin.assessment.index.desc": "Manage quiz questions per skill. Click Detail to view and manage questions in a skill.",
    "admin.assessment.index.btn_add": "Add / Generate Questions",
    "admin.assessment.index.total_questions": "total questions",
    "admin.assessment.index.skills_with_questions": "skills with questions",
    "admin.assessment.index.section_with_questions": "Skills with questions",
    "admin.assessment.index.section_without_questions": "Skills without questions",
    "admin.assessment.index.btn_generate": "Generate",
    "admin.assessment.index.empty_title": "No skills available",
    "admin.assessment.index.empty_desc": "Add a skill first in the Skills menu.",
    "admin.assessment.index.card_active": "active",
    "admin.assessment.index.card_inactive": "inactive",
    "admin.assessment.index.btn_detail": "Detail",
    
    "admin.assessment.show.title": "Question Bank: {skill}",
    "admin.assessment.show.desc": "{total} questions available. Manage, edit, or delete questions for this skill.",
    "admin.assessment.show.search_placeholder": "Search questions...",
    "admin.assessment.show.btn_search": "Search",
    "admin.assessment.show.filter_level": "Level",
    "admin.assessment.show.filter_level_all": "All levels",
    "admin.assessment.show.filter_status": "Status",
    "admin.assessment.show.filter_status_all": "All statuses",
    "admin.assessment.show.status_active": "Active",
    "admin.assessment.show.status_inactive": "Inactive",
    "admin.assessment.show.empty_title": "No questions available",
    "admin.assessment.show.empty_desc": "Generate questions with AI or add manually.",
    "admin.assessment.show.btn_generate_ai": "Generate with AI",
    "admin.assessment.show.dialog_delete_title": "Delete question?",
    "admin.assessment.show.dialog_delete_desc": "This question will be permanently deleted from the bank.",
    "admin.assessment.show.btn_cancel": "Cancel",
    "admin.assessment.show.btn_delete": "Delete",
    "admin.assessment.show.btn_deleting": "Deleting...",
    "admin.assessment.show.btn_edit": "Edit",
    
    "admin.assessment.form.skill": "Skill",
    "admin.assessment.form.skill_placeholder": "Select skill",
    "admin.assessment.form.level": "Level",
    "admin.assessment.form.mode": "Input Mode",
    "admin.assessment.form.mode_manual": "Manual (1 question)",
    "admin.assessment.form.mode_ai": "Generate AI (batch)",
    "admin.assessment.form.ai_count": "AI Question Count",
    "admin.assessment.form.manual_title": "Manual Questions ({count})",
    "admin.assessment.form.btn_add_manual": "Add Question",
    "admin.assessment.form.question_num": "Question #{num}",
    "admin.assessment.form.btn_remove": "Remove",
    "admin.assessment.form.question": "Question",
    "admin.assessment.form.question_placeholder": "Enter your question",
    "admin.assessment.form.option_a": "Option A",
    "admin.assessment.form.option_b": "Option B",
    "admin.assessment.form.option_c": "Option C",
    "admin.assessment.form.option_d": "Option D",
    "admin.assessment.form.correct_answer": "Correct Answer",
    "admin.assessment.form.is_active": "Active question",
    "admin.assessment.form.btn_saving": "Saving...",
    "admin.assessment.form.btn_save_ai": "Generate AI Questions",
    "admin.assessment.form.btn_save_manual": "Save Question",
    "admin.assessment.form.search_skill": "Search skill...",
    "admin.assessment.form.skill_not_found": "Skill not found.",

    "admin.pricing.form.section_info_title": "Package Info",
    "admin.pricing.form.section_info_desc": "Candidate package name, topup price, and publication status.",
    "admin.pricing.form.name": "Package Name",
    "admin.pricing.form.name_placeholder": "E.g.: AI Topup 5,000 Tokens",
    "admin.pricing.form.desc": "Description",
    "admin.pricing.form.desc_placeholder": "Explain the purpose of this package for candidates.",
    "admin.pricing.form.price": "Price",
    "admin.pricing.form.default_free": "Default free package",
    "admin.pricing.form.default_free_desc": "Used for candidate's first CV Builder access.",
    "admin.pricing.form.is_active": "Active package",
    "admin.pricing.form.is_active_desc": "Package can be displayed in the candidate pricing flow.",
    "admin.pricing.form.section_quota_title": "Package Quota",
    "admin.pricing.form.section_quota_desc": "Determine AI token amount and CV Builder usage quota.",
    "admin.pricing.form.ai_token": "AI Token Amount",
    "admin.pricing.form.cv_quota": "CV Builder Quota",
    "admin.pricing.form.section_benefit_title": "Package Benefits",
    "admin.pricing.form.section_benefit_desc": "Write one benefit per line to clearly display on the pricing page.",
    "admin.pricing.form.btn_add_benefit": "Add Benefit",
    "admin.pricing.form.benefit_placeholder": "E.g.: 1x additional CV Builder",
    "admin.pricing.form.preview_title": "Package Preview",
    "admin.pricing.form.status_active": "Active",
    "admin.pricing.form.status_inactive": "Inactive",
    "admin.pricing.form.preview_name_empty": "Candidate Package Name",
    "admin.pricing.form.preview_price_desc": "package price",
    "admin.pricing.form.badge_free": "Default Free Package",
    "admin.pricing.form.badge_topup": "Topup Package",
    "admin.pricing.form.section_save_title": "Save Changes",
    "admin.pricing.form.section_save_desc": "Once saved, a Sonner notification will appear automatically.",
    "admin.pricing.form.btn_saving": "Saving...",
    "admin.pricing.form.btn_save": "Save Package",
    "admin.pricing.form.error_toast": "Please re-check the candidate pricing data.",

    "admin.pricing.show.badge_free": "Default Free",
    "admin.pricing.show.badge_topup": "Topup",
    "admin.pricing.show.status_active": "Active",
    "admin.pricing.show.status_inactive": "Inactive",
    "admin.pricing.show.section_title": "Candidate Pricing",
    "admin.pricing.show.price_desc": "package price",
    "admin.pricing.show.empty_desc": "No package description.",
    "admin.pricing.show.empty_benefit": "No benefits written yet.",
    "admin.pricing.show.audit_title": "Brief Audit",
    "admin.pricing.show.audit_created": "Created at",
    "admin.pricing.show.audit_updated": "Last updated",
    "admin.pricing.show.audit_status": "Status",
    "admin.pricing.show.metric_ai": "AI Token",
    "admin.pricing.show.metric_cv": "CV Builder Quota",
    "admin.pricing.show.metric_type": "Package Type",
    "admin.pricing.show.type_free": "Free",
    "admin.pricing.show.type_topup": "Topup",

    "admin.pricing.index.btn_add": "Add Menu"
};

Object.assign(idData, newId);
Object.assign(enData, newEn);

fs.writeFileSync(idPath, JSON.stringify(idData, null, 4));
fs.writeFileSync(enPath, JSON.stringify(enData, null, 4));

console.log('Translations appended successfully to lang files.');
